version: "3.8"

networks:
  idurar-network:
    driver: bridge

services:
  mongodb:
    image: mongo
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - idurar-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8888:8888"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    networks:
      - idurar-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - idurar-network

volumes:
  mongo_data:
