version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - idurar-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8888:8888"
    env_file:
      - ./backend/.env
    environment:
      - MONGO_URI=mongodb://mongo:27017/idurar
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - idurar-network

volumes:
  mongo_data:

networks:
  idurar-network:
    driver: bridge
