apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krgaurav01/idurar-erp-crm-backend:01
          ports:
            - containerPort: 8888
          env:
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENAI_API_KEY
            - name: RESEND_API
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RESEND_API
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NODE_ENV
            - name: OPENSSL_CONF
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: OPENSSL_CONF
            - name: PUBLIC_SERVER_FILE
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: PUBLIC_SERVER_FILE
